DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
  user_id int PRIMARY KEY,
  user_name VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS TWEETS;

CREATE TABLE TWEETS (
  tweet_id int PRIMARY KEY,
  user_id int,
  tweet_data VARCHAR(255)
);

ALTER TABLE TWEETS ADD FOREIGN KEY (user_id) REFERENCES USERS(user_id);

DROP TABLE IF EXISTS COMMENTS;

CREATE TABLE COMMENTS (
  comment_id int PRIMARY KEY,
  tweet_id int,
  user_id int,
  comment_data VARCHAR(255)
);

ALTER TABLE COMMENTS ADD FOREIGN KEY (user_id) REFERENCES USERS(user_id);
ALTER TABLE COMMENTS ADD FOREIGN KEY (tweet_id) REFERENCES TWEETS(tweet_id);